version: "3.8"

services:
  database:
    image: mysql:8.0.33
    command:
      - "--default-authentication-plugin=mysql_native_password"
    container_name: db
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .dbdata:/var/lib/mysql
  app:
    image: ambientum/php:8.1-nginx
    container_name: app
    volumes:
      - .:/var/www/app
    ports:
      - "88:8080"
    links:
      - database

volumes:
  dbdata: {}